// Fuente del catálogo de iconos (PLAN_REDISENO_V1 §3.2). De aquí sale
// src/iconos/catalogo.json con `npm run iconos:generar`. Se edita ESTO, nunca el JSON.
//
// GRUPOS: cómo se ordena el selector. `tipos` = los business_tipo de Ajustes para los
// que ese grupo sale primero. Un emoji puede estar en varios grupos.
// NOMBRES: emoji → [nombre en español, ...sinónimos para el buscador].

const TODOS = ['restaurante', 'tienda', 'ropa', 'salon', 'farmacia', 'panaderia', 'otro'];

const GRUPOS = [
  { id: 'taqueria', nombre: 'Taquería y antojitos', tipos: ['restaurante'],
    emojis: '🌮 🌯 🫔 🌶️ 🌽 🧅 🥑 🍋 🧀 🫘' },
  { id: 'hamburguesas', nombre: 'Hamburguesas y hot dogs', tipos: ['restaurante'],
    emojis: '🍔 🌭 🍟 🥪 🧅 🧂' },
  { id: 'pollo', nombre: 'Pollo y carnes', tipos: ['restaurante'],
    emojis: '🍗 🐔 🥩 🍖 🥓 🔥' },
  { id: 'pizzeria', nombre: 'Pizzería e italiana', tipos: ['restaurante'],
    emojis: '🍕 🍝 🧀 🍅 🧄 🫒 🍷' },
  { id: 'mariscos', nombre: 'Mariscos', tipos: ['restaurante'],
    emojis: '🦐 🦀 🦞 🐟 🦪 🐙 🦑 🍤' },
  { id: 'desayunos', nombre: 'Desayunos y fonda', tipos: ['restaurante'],
    emojis: '🥞 🧇 🍳 🥚 🥓 🫘 🍲 🥘 🫕 🥣 🥗 🍠' },
  { id: 'japonesa', nombre: 'Japonesa, china y asiática', tipos: ['restaurante'],
    emojis: '🍣 🍱 🍙 🍘 🍤 🍥 🍶 🍜 🍚 🍛 🥟 🥡 🥠 🥢 🍢 🍡 🥮' },
  { id: 'arabe', nombre: 'Árabe', tipos: ['restaurante'],
    emojis: '🥙 🧆 🫓 🍢' },
  { id: 'bar', nombre: 'Bar y cantina', tipos: ['restaurante'],
    emojis: '🍺 🍻 🍷 🍸 🍹 🥃 🍾 🥂 🧊 🧉 🫗 🍶' },
  { id: 'cafe', nombre: 'Cafetería', tipos: ['restaurante', 'panaderia'],
    emojis: '☕ 🫖 🍵 🧋 🥛 🍼 🥐 🧁 🍰' },
  { id: 'jugos', nombre: 'Jugos y aguas', tipos: ['restaurante', 'tienda'],
    emojis: '🥤 🧃 🥥 🍓 🍊 🍍 🥭 🍉 🍋' },
  { id: 'postres', nombre: 'Postres y dulces', tipos: ['restaurante', 'panaderia', 'tienda'],
    emojis: '🍦 🍧 🍨 🍮 🍩 🍪 🎂 🍰 🧁 🥧 🍫 🍬 🍭 🍯 🍿' },
  { id: 'panaderia', nombre: 'Panadería', tipos: ['panaderia', 'restaurante'],
    emojis: '🍞 🥖 🥐 🥯 🥨 🧇 🍩 🫓 🧈 🎂' },
  { id: 'frutas', nombre: 'Frutas', tipos: ['restaurante', 'tienda'],
    emojis: '🍇 🍈 🍉 🍊 🍋 🍌 🍍 🥭 🍎 🍏 🍐 🍑 🍒 🍓 🫐 🥝 🥥' },
  { id: 'verduras', nombre: 'Verduras', tipos: ['restaurante', 'tienda'],
    emojis: '🍅 🥑 🍆 🥔 🥕 🌽 🌶️ 🫑 🥒 🥬 🥦 🧄 🧅 🥜 🫘 🌰 🫒' },
  { id: 'tienda', nombre: 'Tienda y abarrotes', tipos: ['tienda'],
    emojis: '🛒 🥫 🧃 🥤 🍫 🍬 🧻 🧼 🧂 🧈 🥛 🍞 🥚 📱' },
  { id: 'farmacia', nombre: 'Farmacia', tipos: ['farmacia'],
    emojis: '💊 🩹 🌡️ 🧴 😷 🧪 🩺 🧻 🧼' },
  { id: 'ropa', nombre: 'Ropa y calzado', tipos: ['ropa'],
    emojis: '👕 👗 👖 👟 👠 🧢 👜 🧦 🧥 👔 🩳 👙 👒 🎒' },
  { id: 'salon', nombre: 'Salón de belleza', tipos: ['salon'],
    emojis: '💇 💅 💄 ✂️ 💈 🧴 🪮 🪞' },
  { id: 'servicio', nombre: 'Servicio', tipos: ['restaurante'],
    emojis: '🍽️ 🍴 🥄 🔪 🫙 🧑‍🍳 🧾 💳' },
  { id: 'general', nombre: 'General', tipos: TODOS,
    emojis: '📦 🎁 🏷️ ⭐ ✨ 🔥 🛵 🧾 🛍️ 💡 📌 💰 🎉 ❤️ 👍 🏠 🚗 📋 ✅ ⏰ 🔔' },
];

const NOMBRES = {
  '🌮': ['Taco', 'tacos', 'pastor', 'suadero', 'bistec', 'carnitas'],
  '🌯': ['Burrito', 'burritos', 'wrap', 'burro'],
  '🫔': ['Tamal', 'tamales'],
  '🌶️': ['Chile', 'picante', 'salsa', 'jalapeño', 'habanero'],
  '🌽': ['Elote', 'maíz', 'esquite'],
  '🧅': ['Cebolla', 'aros de cebolla'],
  '🥑': ['Aguacate', 'guacamole'],
  '🍋': ['Limón', 'limones'],
  '🧀': ['Queso', 'quesadilla'],
  '🫘': ['Frijoles', 'frijol', 'charros'],
  '🍔': ['Hamburguesa', 'hamburguesas', 'burger'],
  '🌭': ['Hot dog', 'jocho', 'salchicha'],
  '🍟': ['Papas fritas', 'papas', 'francesa'],
  '🥪': ['Sándwich', 'sandwich', 'torta', 'baguette'],
  '🧂': ['Sal', 'salero'],
  '🍗': ['Pollo', 'pierna', 'muslo', 'alitas', 'boneless'],
  '🐔': ['Gallina', 'pollo entero', 'pollo asado'],
  '🥩': ['Carne', 'arrachera', 'bistec', 'corte', 'filete'],
  '🍖': ['Costilla', 'costillas', 'hueso', 'parrillada'],
  '🥓': ['Tocino', 'bacon'],
  '🔥': ['Fuego', 'al carbón', 'asado', 'promoción', 'popular'],
  '🍕': ['Pizza', 'pizzas', 'rebanada'],
  '🍝': ['Espagueti', 'pasta', 'spaghetti', 'fideos'],
  '🍅': ['Jitomate', 'tomate'],
  '🧄': ['Ajo'],
  '🫒': ['Aceituna', 'aceitunas', 'olivo'],
  '🍷': ['Vino tinto', 'vino', 'copa de vino'],
  '🦐': ['Camarón', 'camarones', 'coctel'],
  '🦀': ['Cangrejo', 'jaiba'],
  '🦞': ['Langosta'],
  '🐟': ['Pescado', 'filete de pescado', 'mojarra'],
  '🦪': ['Ostión', 'ostiones', 'ostra'],
  '🐙': ['Pulpo'],
  '🦑': ['Calamar', 'calamares'],
  '🍤': ['Camarón empanizado', 'tempura', 'camarón frito'],
  '🥞': ['Hot cakes', 'hotcakes', 'panqueques'],
  '🧇': ['Waffle', 'wafle', 'gofre'],
  '🍳': ['Huevo estrellado', 'huevos', 'desayuno', 'sartén'],
  '🥚': ['Huevo', 'huevos'],
  '🍲': ['Caldo', 'sopa', 'pozole', 'menudo', 'olla'],
  '🥘': ['Guisado', 'paella', 'cazuela'],
  '🫕': ['Fondue', 'cazuela'],
  '🥣': ['Cereal', 'avena', 'plato hondo', 'bowl'],
  '🥗': ['Ensalada', 'ensaladas', 'verde'],
  '🍠': ['Camote', 'batata'],
  '🍣': ['Sushi', 'nigiri'],
  '🍱': ['Bento', 'caja de comida', 'comida corrida'],
  '🍙': ['Onigiri', 'bola de arroz'],
  '🍘': ['Galleta de arroz'],
  '🍥': ['Kamaboko', 'surimi'],
  '🍶': ['Sake'],
  '🍜': ['Ramen', 'sopa de fideos', 'maruchan'],
  '🍚': ['Arroz', 'arroz blanco'],
  '🍛': ['Curry', 'arroz con curry'],
  '🥟': ['Dumpling', 'empanada', 'gyoza'],
  '🥡': ['Comida china', 'para llevar', 'arroz frito'],
  '🥠': ['Galleta de la fortuna'],
  '🥢': ['Palillos'],
  '🍢': ['Brocheta', 'oden', 'banderilla'],
  '🍡': ['Dango', 'dulce japonés'],
  '🥮': ['Pastel de luna'],
  '🥙': ['Pan árabe', 'shawarma', 'kebab', 'gyro'],
  '🧆': ['Falafel', 'croquetas'],
  '🫓': ['Tortilla', 'pan plano', 'tortillas', 'tlayuda'],
  '🍺': ['Cerveza', 'chela', 'tarro'],
  '🍻': ['Cervezas', 'brindis', 'cubeta'],
  '🍸': ['Martini', 'coctel', 'cóctel'],
  '🍹': ['Bebida tropical', 'coctel', 'piña colada', 'margarita'],
  '🥃': ['Whisky', 'tequila', 'mezcal', 'caballito', 'shot'],
  '🍾': ['Champaña', 'botella', 'descorche'],
  '🥂': ['Copas', 'brindis', 'espumoso'],
  '🧊': ['Hielo', 'bolsa de hielo'],
  '🧉': ['Mate', 'té de hierba'],
  '🫗': ['Servir', 'jarra', 'bebida servida'],
  '☕': ['Café', 'cafe', 'americano', 'capuchino', 'latte'],
  '🫖': ['Tetera', 'té'],
  '🍵': ['Té', 'té verde', 'infusión'],
  '🧋': ['Té de burbujas', 'boba', 'frappé'],
  '🥛': ['Leche', 'vaso de leche'],
  '🍼': ['Biberón', 'mamila'],
  '🥐': ['Cuerno', 'croissant', 'cuernito'],
  '🧁': ['Panqué', 'cupcake', 'magdalena'],
  '🍰': ['Rebanada de pastel', 'pastel', 'tres leches', 'pay'],
  '🥤': ['Refresco', 'soda', 'vaso con popote', 'bebida'],
  '🧃': ['Jugo', 'juguito', 'cajita'],
  '🥥': ['Coco'],
  '🍓': ['Fresa', 'fresas'],
  '🍊': ['Naranja', 'jugo de naranja'],
  '🍍': ['Piña'],
  '🥭': ['Mango'],
  '🍉': ['Sandía'],
  '🍦': ['Helado de cono', 'helado', 'nieve', 'cono'],
  '🍧': ['Raspado', 'granizado', 'hielo raspado'],
  '🍨': ['Helado en copa', 'helado', 'nieve'],
  '🍮': ['Flan', 'pudín'],
  '🍩': ['Dona', 'donas'],
  '🍪': ['Galleta', 'galletas'],
  '🎂': ['Pastel de cumpleaños', 'pastel', 'cumpleaños'],
  '🥧': ['Pay', 'tarta'],
  '🍫': ['Chocolate', 'barra'],
  '🍬': ['Dulce', 'caramelo', 'dulces'],
  '🍭': ['Paleta', 'chupa'],
  '🍯': ['Miel'],
  '🍿': ['Palomitas', 'palomitas de maíz'],
  '🍞': ['Pan', 'pan de caja', 'bolillo'],
  '🥖': ['Baguette', 'bolillo', 'pan francés', 'birote'],
  '🥯': ['Bagel', 'rosca'],
  '🥨': ['Pretzel'],
  '🧈': ['Mantequilla', 'margarina'],
  '🍇': ['Uvas', 'uva'],
  '🍈': ['Melón'],
  '🍌': ['Plátano', 'banana'],
  '🍎': ['Manzana roja', 'manzana'],
  '🍏': ['Manzana verde', 'manzana'],
  '🍐': ['Pera'],
  '🍑': ['Durazno', 'melocotón'],
  '🍒': ['Cerezas', 'cereza'],
  '🫐': ['Moras azules', 'arándanos', 'mora'],
  '🥝': ['Kiwi'],
  '🍆': ['Berenjena'],
  '🥔': ['Papa', 'papas'],
  '🥕': ['Zanahoria'],
  '🫑': ['Pimiento', 'morrón'],
  '🥒': ['Pepino'],
  '🥬': ['Lechuga', 'hojas verdes'],
  '🥦': ['Brócoli'],
  '🥜': ['Cacahuate', 'cacahuates', 'maní'],
  '🌰': ['Castaña', 'nuez'],
  '🛒': ['Carrito', 'súper', 'abarrotes', 'compras'],
  '🥫': ['Lata', 'enlatado', 'conserva'],
  '🧻': ['Papel higiénico', 'papel de baño'],
  '🧼': ['Jabón'],
  '📱': ['Celular', 'recarga', 'teléfono'],
  '💊': ['Pastilla', 'medicina', 'medicamento', 'cápsula'],
  '🩹': ['Curita', 'venda'],
  '🌡️': ['Termómetro', 'temperatura'],
  '🧴': ['Crema', 'loción', 'shampoo', 'botella'],
  '😷': ['Cubrebocas', 'mascarilla'],
  '🧪': ['Laboratorio', 'análisis', 'tubo de ensayo'],
  '🩺': ['Estetoscopio', 'consulta', 'doctor'],
  '👕': ['Playera', 'camiseta', 'remera'],
  '👗': ['Vestido'],
  '👖': ['Pantalón', 'jeans', 'mezclilla'],
  '👟': ['Tenis', 'zapatillas'],
  '👠': ['Zapato de tacón', 'tacones', 'zapatos'],
  '🧢': ['Gorra'],
  '👜': ['Bolsa', 'bolso'],
  '🧦': ['Calcetines', 'calcetas'],
  '🧥': ['Chamarra', 'abrigo', 'chaqueta'],
  '👔': ['Camisa', 'corbata'],
  '🩳': ['Short', 'bermuda'],
  '👙': ['Traje de baño', 'bikini'],
  '👒': ['Sombrero'],
  '🎒': ['Mochila'],
  '💇': ['Corte de pelo', 'corte', 'peinado', 'estética'],
  '💅': ['Uñas', 'manicure', 'pedicure'],
  '💄': ['Labial', 'maquillaje'],
  '✂️': ['Tijeras', 'corte'],
  '💈': ['Barbería', 'barbero'],
  '🪮': ['Peine', 'cepillo'],
  '🪞': ['Espejo'],
  '🍽️': ['Plato', 'platillo', 'comida', 'plato del día'],
  '🍴': ['Cubiertos', 'tenedor', 'comida'],
  '🥄': ['Cuchara'],
  '🔪': ['Cuchillo'],
  '🫙': ['Frasco', 'salsa', 'conserva'],
  '🧑‍🍳': ['Chef', 'cocinero', 'especialidad'],
  '🧾': ['Ticket', 'recibo', 'cuenta'],
  '💳': ['Tarjeta', 'pago'],
  '📦': ['Caja', 'paquete', 'producto'],
  '🎁': ['Regalo', 'promoción', 'combo'],
  '🏷️': ['Etiqueta', 'oferta', 'precio'],
  '⭐': ['Estrella', 'favorito', 'especial'],
  '✨': ['Brillos', 'nuevo', 'novedad'],
  '🛵': ['Moto', 'envío', 'domicilio', 'reparto'],
  '🛍️': ['Bolsas de compras', 'compras'],
  '💡': ['Foco', 'idea'],
  '📌': ['Chincheta', 'fijado'],
  '💰': ['Dinero', 'bolsa de dinero'],
  '🎉': ['Fiesta', 'celebración'],
  '❤️': ['Corazón', 'favorito'],
  '👍': ['Pulgar arriba', 'me gusta'],
  '🏠': ['Casa', 'hogar'],
  '🚗': ['Coche', 'auto', 'carro'],
  '📋': ['Portapapeles', 'lista'],
  '✅': ['Palomita', 'listo'],
  '⏰': ['Reloj', 'alarma', 'horario'],
  '🔔': ['Campana', 'aviso'],
};

// ICONOS PROPIOS (§3.2 del plan): dibujados en el estilo de Fluent, en
// scripts/iconos/nuevos/<id>.svg. Sin emoji: el producto guarda `svg:z-<id>` (trampa 7).
// Cada tanda de cinco, aprobada por el dueño junto a los originales antes de entrar aquí.
const NUEVOS = [
  // Tanda 1 — taquería (aprobada 2026-09-22)
  { id: 'torta', nombre: 'Torta', buscar: ['tortas', 'bolillo', 'telera', 'lonche'], grupos: ['taqueria', 'hamburguesas'] },
  { id: 'quesadilla', nombre: 'Quesadilla', buscar: ['quesadillas', 'sincronizada', 'gringa'], grupos: ['taqueria'] },
  { id: 'sope', nombre: 'Sope', buscar: ['sopes', 'gordita', 'huarache', 'tostada'], grupos: ['taqueria'] },
  { id: 'esquite', nombre: 'Esquite', buscar: ['esquites', 'elote en vaso', 'vasito'], grupos: ['taqueria'] },
  { id: 'pozole', nombre: 'Pozole', buscar: ['pozole rojo', 'caldo', 'menudo', 'birria', 'consomé'], grupos: ['taqueria', 'desayunos'] },
  // Tanda 2 — bar (aprobada 2026-09-22)
  { id: 'michelada', nombre: 'Michelada', buscar: ['michelado', 'chelada', 'clamato', 'cerveza preparada'], grupos: ['bar'] },
  { id: 'caguama', nombre: 'Caguama', buscar: ['caguamón', 'cerveza', 'botella', 'ballena', 'litro'], grupos: ['bar', 'tienda'] },
  { id: 'cubeta', nombre: 'Cubeta de cervezas', buscar: ['cubeta', 'cervezas', 'promoción', 'six'], grupos: ['bar'] },
  { id: 'caballito', nombre: 'Caballito', buscar: ['shot', 'tequila', 'trago', 'chupito'], grupos: ['bar'] },
  { id: 'mezcal', nombre: 'Mezcal', buscar: ['copita', 'jícara', 'mezcalito', 'trago'], grupos: ['bar'] },
  // Tanda 3 — postres (aprobada 2026-09-22)
  { id: 'churros', nombre: 'Churros', buscar: ['churro', 'churrería'], grupos: ['postres', 'cafe'] },
  { id: 'paleta_hielo', nombre: 'Paleta de hielo', buscar: ['paleta', 'paletería', 'helado de agua', 'bolis'], grupos: ['postres'] },
  { id: 'nieve_vaso', nombre: 'Nieve en vaso', buscar: ['nieve', 'helado', 'bolas de helado', 'nevería'], grupos: ['postres'] },
  { id: 'fresas_crema', nombre: 'Fresas con crema', buscar: ['fresas', 'crema', 'postre de fresa'], grupos: ['postres'] },
  { id: 'crepa', nombre: 'Crepa', buscar: ['crepas', 'nutella', 'crepería'], grupos: ['postres', 'cafe'] },
  // Tanda 4 — jugos y aguas (aprobada 2026-09-22)
  { id: 'agua_fresca', nombre: 'Agua fresca', buscar: ['agua de jamaica', 'horchata', 'jarra', 'agua de sabor'], grupos: ['jugos'] },
  { id: 'licuado', nombre: 'Licuado', buscar: ['licuados', 'malteada', 'smoothie', 'batido'], grupos: ['jugos', 'desayunos'] },
  { id: 'raspado', nombre: 'Raspado', buscar: ['raspados', 'granizado', 'hielo raspado', 'diablito'], grupos: ['jugos', 'postres'] },
  { id: 'coco_popote', nombre: 'Coco con popote', buscar: ['coco', 'agua de coco'], grupos: ['jugos'] },
  { id: 'jugo_verde', nombre: 'Jugo verde', buscar: ['jugo', 'verde', 'detox', 'nopal'], grupos: ['jugos', 'desayunos'] },
  // Tanda 5 — mariscos (aprobada 2026-09-22)
  { id: 'coctel_camaron', nombre: 'Coctel de camarón', buscar: ['coctel', 'campechana', 'vuelve a la vida', 'copa'], grupos: ['mariscos'] },
  { id: 'ceviche', nombre: 'Ceviche', buscar: ['cebiche', 'ceviche de pescado'], grupos: ['mariscos'] },
  { id: 'aguachile', nombre: 'Aguachile', buscar: ['aguachiles', 'camarón', 'molcajete'], grupos: ['mariscos'] },
  { id: 'tostada_marisco', nombre: 'Tostada de marisco', buscar: ['tostada', 'tostadas', 'tostada de ceviche', 'atún'], grupos: ['mariscos', 'taqueria'] },
  { id: 'mojarra_frita', nombre: 'Mojarra frita', buscar: ['pescado frito', 'mojarra', 'pescado', 'huachinango'], grupos: ['mariscos'] },
  // Tanda 6 — cafetería y panadería (2026-09-22)
  { id: 'frappe', nombre: 'Frappé', buscar: ['frapuccino', 'café frío', 'moka', 'frappe'], grupos: ['cafe'] },
  { id: 'cafe_olla', nombre: 'Café de olla', buscar: ['café', 'olla', 'canela', 'jarrito'], grupos: ['cafe', 'desayunos'] },
  { id: 'capuchino', nombre: 'Capuchino', buscar: ['cappuccino', 'latte', 'café con leche', 'arte latte'], grupos: ['cafe'] },
  { id: 'concha', nombre: 'Concha', buscar: ['conchas', 'pan dulce', 'pan de dulce'], grupos: ['panaderia', 'cafe'] },
  { id: 'rol_canela', nombre: 'Rol de canela', buscar: ['rol', 'canela', 'cinnamon roll', 'pan dulce'], grupos: ['panaderia', 'cafe'] },
  // Tanda 7 — panadería y antojitos (2026-09-22)
  { id: 'bolillo', nombre: 'Bolillo', buscar: ['bolillos', 'telera', 'pan salado', 'birote'], grupos: ['panaderia'] },
  { id: 'tres_leches', nombre: 'Pastel de tres leches', buscar: ['tres leches', 'pastel', 'rebanada'], grupos: ['postres', 'panaderia'] },
  { id: 'tlayuda', nombre: 'Tlayuda', buscar: ['tlayudas', 'clayuda', 'oaxaca', 'tasajo'], grupos: ['taqueria'] },
  { id: 'chilaquiles', nombre: 'Chilaquiles', buscar: ['chilaquil', 'totopos', 'rojos', 'verdes'], grupos: ['desayunos', 'taqueria'] },
  { id: 'trompo', nombre: 'Trompo al pastor', buscar: ['trompo', 'pastor', 'al pastor', 'orden de pastor'], grupos: ['taqueria'] },
  // Tanda 8 — desayunos y fonda (2026-09-22)
  { id: 'huevos_rancheros', nombre: 'Huevos rancheros', buscar: ['huevos', 'rancheros', 'huevos estrellados'], grupos: ['desayunos'] },
  { id: 'enchiladas', nombre: 'Enchiladas', buscar: ['enchilada', 'entomatadas', 'enmoladas', 'suizas'], grupos: ['desayunos', 'taqueria'] },
  { id: 'molletes', nombre: 'Molletes', buscar: ['mollete', 'pan con frijoles'], grupos: ['desayunos'] },
  { id: 'comida_corrida', nombre: 'Comida corrida', buscar: ['menú del día', 'plato del día', 'comida', 'fonda', 'paquete'], grupos: ['desayunos'] },
  { id: 'bowl', nombre: 'Bowl', buscar: ['poke', 'ensalada', 'tazón', 'saludable', 'vegano'], grupos: ['desayunos'] },
  // Tanda 9 — pollo y asador (2026-09-22)
  { id: 'alitas', nombre: 'Alitas', buscar: ['alas', 'wings', 'búfalo', 'bbq'], grupos: ['pollo', 'bar'] },
  { id: 'pollo_asado', nombre: 'Pollo asado', buscar: ['pollo rostizado', 'pollo entero', 'pollo al carbón'], grupos: ['pollo'] },
  { id: 'cubeta_pollo', nombre: 'Cubeta de pollo', buscar: ['pollo frito', 'piezas', 'cubeta', 'familiar'], grupos: ['pollo'] },
  { id: 'arrachera', nombre: 'Arrachera', buscar: ['carne asada', 'corte', 'bistec', 'sirloin'], grupos: ['pollo'] },
  { id: 'costillas', nombre: 'Costillas', buscar: ['costillitas', 'ribs', 'bbq', 'cerdo'], grupos: ['pollo'] },
  // Tanda 10 — asador, hamburguesas e italiana (2026-09-22)
  { id: 'parrillada', nombre: 'Parrillada', buscar: ['asador', 'carne asada', 'chorizo', 'parrilla'], grupos: ['pollo'] },
  { id: 'papas_canasta', nombre: 'Papas en canasta', buscar: ['papas', 'papas fritas', 'francesas', 'canasta'], grupos: ['hamburguesas', 'bar'] },
  { id: 'boneless', nombre: 'Boneless', buscar: ['boneles', 'pollo sin hueso', 'nuggets', 'tenders'], grupos: ['hamburguesas', 'pollo', 'bar'] },
  { id: 'lasana', nombre: 'Lasaña', buscar: ['lasagna', 'lasaña', 'pasta'], grupos: ['pizzeria'] },
  { id: 'calzone', nombre: 'Calzone', buscar: ['calzón', 'empanada', 'pizza cerrada'], grupos: ['pizzeria'] },
  // Tanda 11 — asiática (2026-09-22)
  { id: 'maki', nombre: 'Rollo de sushi', buscar: ['maki', 'sushi', 'rollo', 'california'], grupos: ['japonesa'] },
  { id: 'ramen', nombre: 'Ramen', buscar: ['sopa japonesa', 'fideos', 'noodles'], grupos: ['japonesa'] },
  { id: 'onigiri_salmon', nombre: 'Onigiri de salmón', buscar: ['onigiri', 'salmón', 'bola de arroz'], grupos: ['japonesa'] },
  { id: 'arroz_frito', nombre: 'Arroz frito', buscar: ['arroz chino', 'chaufa', 'yakimeshi'], grupos: ['japonesa'] },
  { id: 'pollo_agridulce', nombre: 'Pollo agridulce', buscar: ['agridulce', 'pollo a la naranja', 'chino'], grupos: ['japonesa'] },
  // Tanda 12 — árabe (2026-09-22). El shawarma se tiró: se veía como vaso; queda el 🥙 de Microsoft
  { id: 'taco_arabe', nombre: 'Taco árabe', buscar: ['tacos árabes', 'pan árabe', 'puebla'], grupos: ['arabe', 'taqueria'] },
  { id: 'kibbe', nombre: 'Kibbe', buscar: ['kibi', 'quipe', 'kepe'], grupos: ['arabe'] },
  { id: 'hummus', nombre: 'Hummus', buscar: ['humus', 'garbanzo', 'dip'], grupos: ['arabe'] },
  { id: 'wrap', nombre: 'Wrap', buscar: ['burrito', 'rollo', 'sincronizada', 'saludable'], grupos: ['arabe', 'desayunos'] },
];

module.exports = { GRUPOS, NOMBRES, NUEVOS, TODOS };
